[profile.default]
src = "src"
out = "out"
libs = ["lib"]


optimizer = true
optimizer_runs = 1000000

# --compiler-version = "v0.8.23+commit.f704f362"
# yul = true
# viaIR = true

[fmt]
line_length = 100
tab_width = 2
int_types = "short"


[rpc_endpoints]
arbitrum-sepolia = "${RPC_URL}"

[etherscan]
arbitrum-sepolia = { key = "${ETHERSCAN_API_KEY}", url = "https://api-sepolia.arbiscan.io/api" }
